version: 0.2

phases: 
  build: 
    commands: 
      - echo entered the build phase.. 
      - mvn clean package

  post_build: 
    commands: 
      - echo Build completed successfully
      
artfacts: 
  files:
    - target/exception-handler.jar
  discard-paths: yes